### ISSUE TITLE
How to install php-xml in container?

### ISSUE THREAD

**Issue by migoth** [a-kom/docker-compose-lamp#3]
I need to install php-xml in a docker container.
How can i do this?

**Comment by akhomy** [comment]
@Migoth, in what container do you need this?
Pls, provide here the container name.

**Comment by migoth** [comment]
I need to install php-xml into the php-fpm container.

**Comment by akhomy** [comment]
Oh, I'm sorry, but I didn't add this feature like other stacks, you could add this as issue to https://github.com/a-kom/alpine-php_fpm/blob/php-7/Dockerfile, make fork and I'll merge it, or you need to create your own image from my and install in it.

**Comment by migoth** [comment]
Is it not possible to add a command in docker-compose.yml?

**Comment by akhomy** [comment]
Sorry, but currently no, if it is very important for you I could add it directly now, could you provide list of necessary extensions? I think php-xml is a good point to be in the image from the box.
And I think as a point I could add builded locally image, where you could add some necessary updates. But it will be added later.

**Comment by migoth** [comment]
I like to use:

- php-xml
- php-zip
- curl
- memcached
- phpunit

**Comment by andrii-khomych-lemberg-co-uk** [comment]
@Migoth, seems you are using the PHP-5 image, I added php-xml for PHP-5 pls wait near 30 minutes until it is building. php-memcache and php-curl were from box. You could add PHPUnit for your project via composer. Also, I'll add later build image where you could add your own extensions.

**Comment by migoth** [comment]
@andrii-khomych-lemberg-co-uk no im using PHP-7 ^^
but thanks

**Comment by akhomy** [comment]
@Migoth, so as you could see https://github.com/a-kom/alpine-php_fpm/blob/php-7/Dockerfile there are:
php7-xml
php7-zip
php7-curl
memcached from https://github.com/php-memcached-dev/php-memcached
and built in composer if you need some extra packages.

**Comment by akhomy** [comment]
@Migoth, you can uncomment line `# build: docker/images/php-fpm/.` in the `docker-compose.yml` and comment image line. Then you can add any extensions and edit them in file docker/images/php-fpm/Dockerfile

**Comment by akhomy** [comment]
@Migoth, pls, reply if it is enough for you and it works.
