### ISSUE TITLE
MariaDB is aborting always

### ISSUE THREAD

**Issue by uebmaster** [a-kom/docker-compose-lamp#5]
even if you restart the container, it always aborts, i change the label to the last one to see if this worked but keep doing the same

![image](https://user-images.githubusercontent.com/5565506/36129812-a5d50be2-102e-11e8-839e-8e334302b27b.png)

**Comment by akhomy** [comment]
Hi, @uebmaster.  First, you can check - https://github.com/a-kom/docker-compose-lamp/issues/4. Second, Could you provide your `docker-compose.yml` file? Also, please provide your docker toolbox version, windows version and would be good to have an archive that you use to run.

**Comment by uebmaster** [comment]
This works for me but changing to mysql

_docker-compose stop && docker-compose rm -f
Remove folder docker/runtime/mysql
Run docker-compose up -d
I'm not sure if this help in this case, but you'll recreate from scratch and run on clean docker containers.
Also, I'll check this on Windows today later._

**Comment by uebmaster** [comment]
i am not using docker toolbox, i am using docker for windows, windows 10 pro, and i am using your repository cloned.

Thanks for reply.

**Comment by akhomy** [comment]
Hi @uebmaster, I'm glad that this help. If you want to continue using mariadb you could try to change the `mariadb:10.0` to simple `mariadb`. I think it could help too.

**Comment by uebmaster** [comment]
I tried but doesn’t Works, only with mysql works
