### ISSUE TITLE
Cannot connect to PHPMyAdmin

### ISSUE THREAD

**Issue by erralb** [a-kom/docker-compose-lamp#7]
Hi,

When I try to connect to the phpMyAdmin, I'm getting the following errors:

```
 mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve
 mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

I have been searching internet and tried various found solutions but nothing worked, could you help please?

I am using Fedora 29

**Comment by akhomy** [comment]
Hi, @erralb, please, attach your docker-compose.yml file. Versions of docker and docker-compose.

**Comment by erralb** [comment]
hey thanks for getting back. 
It wasn't working with the latest MySQL version (8) so I tried with MySQL v5 and had this issue.

I ended up trying again with MySQL 8 and sorting the authentication problem ( [StackOverflow](https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0) ) solved it, now it's working... Sorry for the bother!
