### ISSUE TITLE
is it enabled to install some version of php 8.X?

### ISSUE THREAD

**Issue by wnunezc** [a-kom/docker-compose-lamp#8]
is it enabled to install some version of php 8.X?

**Comment by akhomy** [comment]
Hey, sorry, unfortunately I didn't have time to implement it.
This is a valid feature request but the whole stack is going to be reworked by using official PHP images and some other stuff.

**Comment by arcanisgk** [comment]
ok

**Comment by wnunezc** [comment]
ok
